### ISSUE TITLE
decodeAudioData does not resolve an AudioBufferMock

### ISSUE THREAD

**Issue by KatherineWinter** [chrisguttandin/standardized-audio-context-mock#327]
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData

decodeAudioData should return an AudioBufferMock.

**Comment by chrisguttandin** [comment]
Hi Kathrine, thanks for raising this issue.

So far only those functions are implemented which have been requested. Please let me know if there is something else you're missing. PRs are welcome as well.

The fix should be available from v7.1.23 onwards.
