### ISSUE TITLE
Parity with standardized-audio-context's exports

### ISSUE THREAD

**Issue by JackCA** [chrisguttandin/standardized-audio-context-mock#340]
I'm trying to use this in my Jest tests to completely mock all `standardized-audio-context` exports and would like to ideally just do something like:
```javascript
import * as StandardizedAudioContextMock from 'standardized-audio-context-mock'
jest.mock('standardized-audio-context', () => StandardizedAudioContextMock)
```

but it looks like some exports don't exist like `isAnyAudioContext`.

Is there a better approach than this, or should the missing exports be added?

**Comment by chrisguttandin** [comment]
Hi @JackCA, version 8.2 does now contain all the exports that are exported by `standardized-audio-context` as well. However the classes don't have all expected properties and functions. Please let me know which of the functionality you are missing.

**Comment by JackCA** [comment]
Nice! I think you got the exports handled. Thank you so much.

I'm running into a different issue now though (and can open another issue):

I get:
 > `TypeError: Cannot set property onstatechange of #<AudioContextMock> which has only a getter` 

because [the mock `AudioContext` has a readonly `onstatechange`](https://github.com/chrisguttandin/standardized-audio-context-mock/blob/master/src/audio-context-mock.ts#L75-L77) but I believe [it should be writable](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/onstatechange).

**Comment by JackCA** [comment]
Closing since this specific issue is complete :peace_symbol:
