### ISSUE TITLE
StereoPannerNode is not implemented

### ISSUE THREAD

**Issue by danigb** [chrisguttandin/standardized-audio-context-mock#363]
See https://github.com/chrisguttandin/standardized-audio-context-mock/blob/master/src/stereo-panner-node-mock.ts

The most important thing I need is to be able to connect other components.

Do you want me to do a PR?

**Comment by chrisguttandin** [comment]
Thanks for your suggestion. There are still far too many todo comments in this library. :-)

I went ahead and added a basic implementation for the `StereoPannerNode`. v9.1.0 includes the update.

**Comment by danigb** [comment]
Thanks @chrisguttandin
