### ISSUE TITLE
`connect` is not chainable

### ISSUE THREAD

**Issue by kirbysayshi** [chrisguttandin/standardized-audio-context-mock#364]
`node0.connect(node1).connect(node2)` will throw if using this library. Unless I'm doing something wrong? I'm surprised this hasn't been an issue before.

It's probably because the `spy` doesn't know to return the incoming node! https://github.com/chrisguttandin/standardized-audio-context-mock/blob/master/src/audio-node-mock.ts#L39

I'm not as familiar with sinon, but I'm guessing it will need to be changed to a `stub()`.

**Comment by chrisguttandin** [comment]
Hi @kirbysayshi, thanks for filing this issue.

You are absolutely right it should be a `stub()` that returns the `destination`. It should work now.

There are still a lot of missing pieces in this package. Since reaching full compatibility with the Web Audio API (or standardized-audio-context) is a daunting task I more or less only implement the parts which are actually used. Please let me know if you run into any other issues.

**Comment by kirbysayshi** [comment]
Thanks, and totally understandable @chrisguttandin! The mere presence of this library is very helpful! Thanks for making it.

The only other piece that was recently missing for me was MediaStreamAudioDestinationNode. I worked around it like this:

```ts
import { TContext } from 'standardized-audio-context';
import {
  AudioContext as MockAudioContext,
  AudioNode as AudioNodeMock,
} from 'standardized-audio-context-mock';

window.MediaStream = class MockMediaStream {
  getAudioTracks() {
    return [];
  }
} as unknown as typeof MediaStream;

class MediaStreamAudioDestinationNodeMock<
  T extends TContext
> extends AudioNodeMock<T> {
  stream: MediaStream = new MediaStream();
}

// somewhere in a test:
const ctx = new MockAudioContext();
ctx.createMediaStreamDestination = () =>
  ({
    stream: new MediaStream(),
  } as unknown as MediaStreamAudioDestinationNodeMock<MockAudioContext>);
return ctx as unknown as AudioContext;
```

I don't think it's practical to provide an entire MediaStream mock/stub included with standardized-audio-context-mock, since it's a complex and mostly separate API (unless you figure out something reasonable)!

As you can _maybe_ see I was using standardized-audio-context-mock as a general purpose Web Audio API mock 😲 😎   What made the above snippet a little trickier to figure out is that the app I'm working on needs the native AudioContext. Many libraries rely on ScriptProcessorNode being present. Luckily in my test, none of them were actually going to execute! But the use of `unknown` was mandatory to pass typechecking, especially because `IMediaStreamAudioDestinationNode` is present but unimplemented in the `MockAudioContext`.

**Comment by chrisguttandin** [comment]
Yes, I agree. Mocking the `MediaStream` itself is a bit out of scope.

I added a basic implementation of the `MediaStreamAudioDestinationNode` which relies on a globally available `MediaStream`. It hopefuly allows you to remove a part of your workaround.

https://github.com/chrisguttandin/standardized-audio-context-mock/commit/df2b6145710343f55a93c93f8dbb64b914b767c1

**Comment by kirbysayshi** [comment]
Excellent! Thank you very much :D

**Comment by kirbysayshi** [comment]
Oh, does https://github.com/chrisguttandin/standardized-audio-context-mock/commit/df2b6145710343f55a93c93f8dbb64b914b767c1 need to include `context.createMediaStreamDestination()`? Or does standardized-audio-context not include the factory methods?

**Comment by chrisguttandin** [comment]
Oh sorry, I forgot to wire that up. It should work now.

https://github.com/chrisguttandin/standardized-audio-context-mock/commit/381a3325bf85b862b252049cf5f13d963fe56717

**Comment by kirbysayshi** [comment]
It's working perfectly! Thank you so much 🎉 🙇 🙏
