### ISSUE TITLE
createMediaStreamSource is missing

### ISSUE THREAD

**Issue by Chaoste** [chrisguttandin/standardized-audio-context-mock#86]
Hi,
I'm setting up a listener for my video stream and recognize if a person is speaking loud.
My code looks like this: 
```
  setupListener() {
    const audioContext = new AudioContext();
    const analyser = audioContext.createAnalyser();
    analyser.smoothingTimeConstant = VoiceAnalyzer.SMOOTHING;
    analyser.fftSize = VoiceAnalyzer.FFT_SIZE;
    // $FlowFixMe: The AudioContext definition doesn't accept a stream parameter
    const microphone = audioContext.createMediaStreamSource(this.props.stream);
    const audioProcessor = audioContext.createScriptProcessor(VoiceAnalyzer.BUFFER_SIZE, 1, 1);
    microphone.connect(analyser);
    analyser.connect(audioProcessor);
    audioProcessor.connect(audioContext.destination);
    audioProcessor.onaudioprocess = this.analyseAudio.bind(this);
    this.audioContext = audioContext;
    this.analyser = analyser;
  }
```

Thanks to you I'm able to test this code, but right now it's not working correctly because "createMediaStreamSource" is missing. Can you add this? Here the documentation from MDN:
[MDN - createMediaStreamSource](https://developer.mozilla.org/de/docs/Web/API/AudioContext/createMediaStreamSource)

Thanks in advance!
Thomas

**Comment by Chaoste** [comment]
Just found the [web-audio-test-api](https://github.com/mohayonao/web-audio-test-api) :p

**Comment by chrisguttandin** [comment]
Yes, web-audio-test-api is probably what you want to use. Feel free to reopen that issue again if it doesn't work for you.
